---
output:
  pdf_document:
    keep_tex: true
    fig_caption: true
    toc: true
    toc_depth: 3 
    number_sections: true
    citation_package: natbib
    latex_engine: pdflatex
    template: ./../latex-templates/report.tex
  html_document:
    df_print: paged
    
title: "A boring (academic) title or a clever title?"
subtitle: "A secondary title"
author: 
- name: "YOUR NAME HERE"
  affiliation: "Washington State University"
keywords: |
    multiple comparisons to control; multivariate chi-square distribution; nonlinear growth curves; Richard's curve; simulated critical points
abstract: |
  In this article we compare the \emph{empirical characteristic function} \citep{Tukey:1977, Becker:1988} to a \emph{moment-generating-functional form} to compute the proportion of hypotheses $m$ that are rejected under the null hypothesis. \vspace{0.25in}
  \noindent Here is a second paragraph of the abstract (if necessary), and with the pipe notation it doesn't break. Notice it still needs to be indented. \vspace{0.25in}
  \noindent Generally, we write this abstract last.  Often it is called the executive summary. It should succinctly summarize the entire document.  You can include references such as this one to the Appendices section \ref{sec:appendix} if necessary.
sectionnumberdepth: 3
titleEndnotes: "ENDNOTES"
titleReferences: "REFERENCES"
columnsReferences: 2
titleTOC:  "TABLE OF CONTENTS"
bibliography: ./../biblio/master.bib
bibliostyle: ./../biblio/ormsv080.bst
date: "`r format(Sys.time(), '%B %d, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,appendix-setup,message=FALSE}
library(devtools);       # required for source_url
path.humanVerseWSU = "https://raw.githubusercontent.com/MonteShaffer/humanVerseWSU/"
source_url( paste0(path.humanVerseWSU,"master/misc/functions-project-measure.R") );
source_url( paste0(path.humanVerseWSU,"master/humanVerseWSU/R/functions-dataframe.R") );
source_url( paste0(path.humanVerseWSU,"master/humanVerseWSU/R/functions-EDA.R") );
```

Below is the code to load the data and prepare it for analysis.

```{r,appendix-secret,message=FALSE}
path.project = "C:/_git_/WSU_STATS419_FALL2020/project-measure/";
path.to.secret = "C:/Users/13608/Dropbox/WSU-419/Fall 2020/__student_access__/_SECRET_/";
measure = utils::read.csv( paste0(path.to.secret, "measure-students.txt"), header=TRUE, quote="", sep="|");
getOne = c("hand.length", "hand.width", "hand.elbow", "elbow.armpit", "arm.reach", "foot.length", "floor.kneepit", "floor.hip", "floor.armpit");
n.rows = dim(measure)[1];


for(one in getOne)
  {
  measure[one] = NA;
  }
  
for(i in 1:n.rows)
  {  
  measure.row = measure[i,];
  for(one in getOne)
    {
    nidx = getIndexOfDataFrameColumns(measure, one);
    
    myleft = paste0(one,".left");
      lidx = getIndexOfDataFrameColumns(measure.row, myleft);
    myright = paste0(one,".right");
      ridx = getIndexOfDataFrameColumns(measure.row, myright);
    
      print(paste0(
                  "left: ",myleft," --> ",lidx,
                  " right: ",myright," --> ",ridx
                  )
            );
      
      row.m = mean(
            c(as.numeric(unlist(measure.row[lidx])),
            as.numeric(unlist(measure.row[ridx]))),
            na.rm=TRUE);
      
    measure[i,nidx] =  row.m;
    }
}



#path.github = "https://raw.githubusercontent.com/this-IS-YOUR-PATH-TO-GITHUB/";
#source_url( paste0(path.github,"master/functions/functions-project-measure.R") );

# this is your function
# put in the same "units"
# merge left/right
# build proportion data
# and so on ... 
#measure.df = prepareMeasureData(measure);
```


```{r}
nrow = nrow(measure);
ncol = ncol(measure);
myUnits = tolower(measure$units);
myUnits[myUnits=="inches"] = "in";
myUnits[myUnits=="inch"] = "in";
myUnits[myUnits=="\"in\""] = "in";
measure$my.units = myUnits;
myEthnicity = tolower(measure$ethnicity);
myEthnicity[myEthnicity=="white"] = "w";
myEthnicity[myEthnicity=="caucasian"] = "w";
myEthnicity[myEthnicity=="caucasain"] = "w";
myEthnicity[myEthnicity=="\"caucasian\""] = "w";
myEthnicity[myEthnicity=="anglo"] = "w";
myEthnicity[myEthnicity=="white non-hispanic"] = "w";
myEthnicity[myEthnicity=="black"] = "b";
myEthnicity[myEthnicity=="african american"] = "b";
myEthnicity[myEthnicity=="hispanic"] = "h";
myEthnicity[myEthnicity=="japanese"] = "j";
myEthnicity[myEthnicity=="filipino"] = "f";
myEthnicity[myEthnicity=="native american"] = "nat";
myEthnicity[myEthnicity=="latin american"] = "l";
myEthnicity[myEthnicity=="latino"] = "l";
myEthnicity[myEthnicity=="\"asian/latino\""] = "al";
myEthnicity[myEthnicity=="white-filipino"] = "wf";
myEthnicity[myEthnicity=="asain"] = "a";
myEthnicity[myEthnicity=="asian"] = "a";
myEthnicity[myEthnicity=="\"asian\""] = "a";
myEthnicity[myEthnicity=="chinese"] = "c";
myEthnicity[myEthnicity=="laotian"] = "lao";
myEthnicity[myEthnicity=="caucasian/asian"] = "ca";
myEthnicity[myEthnicity=="white italian"] = "wi";
myEthnicity[myEthnicity=="japanese italian"] = "ji";
myEthnicity[myEthnicity=="pacific islander"] = "pi";
myEthnicity[myEthnicity=="korean"] = "k";
myEthnicity[myEthnicity=="indian"] = "i";
measure$my.ethnicity = myEthnicity;
myGender = tolower(measure$gender);
myGender[myGender=="female"] = "f";
myGender[myGender=="male"] = "m";
myGender[myGender=="\"male\""] = "m";
myGender[myGender=="\"female\""] = "f";
myGender[myGender=="non-binary"] = "o";
measure$my.gender = myGender;

measure$new.units = "cm";
```


```{r covert_unit}
skip = c("minutes", "age", "quality");
## converting everything to cm
for(r in 1:nrow)
  {
  row = measure[r,];
  mynames = names(row);
  if(row$my.units == "in")
    {
    for(c in 1:ncol)
      {
      myname = mynames[c];
      if(!is.element(myname, skip))
        {
        myval = unlist(row[c]);
        print(paste0("r: ",r, " c: ", c," ... old: ",myval, "  ", is.numeric(myval), "   "));
        if(is.numeric(myval))
          {
          newval = myval * 2.54; # 2.54 cm = 1 in
          measure[r,c] = newval;
  print(paste0(" --> ",newval));
          }
        }
      }
    }
  }
```

```{r save_RDS}
measure.short = measure[,c(1,2,4:6,17,24,27:50)];
myNames = gsub(".NA","", colnames(measure.short), fixed=TRUE);
colnames(measure.short) = myNames;
colnames(measure.short)[11] = "eye.color"


```

```{r}
saveRDS(measure,"measure.rds");
measure.short = measure[,c(1,2,4:6,17,24,27:50)];
myNames = gsub(".NA","", colnames(measure.short), fixed=TRUE);
colnames(measure.short) = myNames;
colnames(measure.short)[11] = "eye.color";
measure.df = removeDuplicatesFromDataFrameAllColumns(measure.short);

measure.df
saveRDS(measure.df,"measure.df.rds");
# 411f8b5c9500b7cc928c93dd1a0006b7
# 7e6e6a69493f1d54a74ecdd4058ebadf 81a9f3915f64dc6edd329b89bea87d5e 182.88000
# 	9eb3d5323b1a3c511c3b8c8038727737  "ee33e909372d935d190f4fcb2a92d542"  10.75000

```


```{r}
final.df = measure.df;
final.df = subsetDataFrame(final.df, "data_collector", "!=", "411f8b5c9500b7cc928c93dd1a0006b7");
final.df = subsetDataFrame(final.df, "person_id", "!=", "81a9f3915f64dc6edd329b89bea87d5e");
final.df = subsetDataFrame(final.df, "person_id", "!=", "\"ee33e909372d935d190f4fcb2a92d542\"");

myEye = tolower(final.df$eye);
myEye[myEye == "both"] = "b";
myEye[myEye == "\"both\""] = "b";
myEye[myEye == "equal"] = "b";
myEye[myEye == "right"] = "r";
myEye[myEye == "\"right\""] = "r";
myEye[myEye == "left"] = "l";
myEye[myEye == "\"left\""] = "r";
myEye[myEye == "brown"] = NA;
final.df$my.eye = factor(myEye);
myWriting = tolower(final.df$writing);
myWriting[myWriting == "right"] = "r";
myWriting[myWriting == "\"right\""] = "r";
myWriting[myWriting == "left"] = "l";
myWriting[myWriting == "both"] = "b";
final.df$my.writing = factor(myWriting);
mySwinging = tolower(final.df$swinging);
mySwinging[mySwinging == "right"] = "r";
mySwinging[mySwinging == "rigth"] = "r";
mySwinging[mySwinging == "\"right\""] = "r";
mySwinging[mySwinging == "left"] = "l";
mySwinging[mySwinging == "let"] = "l";
mySwinging[mySwinging == "leftt"] = "l";
mySwinging[mySwinging == "both"] = "b";
final.df$my.swinging = factor(mySwinging);
myEyeColor = tolower(final.df$eye.color);
myEyeColor[myEyeColor == "brown"] = "br";
myEyeColor[myEyeColor == "\"brown\""] = "br";
myEyeColor[myEyeColor == "blue"] = "bl";
myEyeColor[myEyeColor == "\"blue\""] = "bl";
myEyeColor[myEyeColor == "green"] = "gr";
myEyeColor[myEyeColor == "hazel"] = "ha";
myEyeColor[myEyeColor == "grey"] = "g";
myEyeColor[myEyeColor == "blue-green"] = "bl-gr";
myEyeColor[myEyeColor == "blue/green"] = "bl-gr";
myEyeColor[myEyeColor == "blue-grey"] = "bl-g";
myEyeColor[myEyeColor == "grey-green"] = "gr-g";
myEyeColor[myEyeColor == "black"] = "b";
myEyeColor[myEyeColor == "left"] = NA;
final.df$my.eye.color = factor(myEyeColor);
final.df$my.gender = factor(final.df$my.gender);
final.df$my.ethnicity = factor(final.df$my.ethnicity);
# measure.nic = subsetDataFrame(measure.short, "data_collector", "==", "0185c7c2eed9d48197953305a817c8b1");
# measure.nic2 = subsetDataFrame(measure.df, "data_collector", "==", "0185c7c2eed9d48197953305a817c8b1");
# 411f8b5c9500b7cc928c93dd1a0006b7
final.df$person_id = trimMe( gsub('"',"",final.df$person_id,fixed=TRUE) );
saveRDS(final.df,"final.measure.rds");
	utils::write.table(final.df, file="final.measure.txt", quote=FALSE, col.names=TRUE, row.names=FALSE, sep="|");

summary(final.df)

```
```{r correlation}
measure.cor <-cor(na.omit(final.df[,c(3:7,13,19:27)]))
library(corrgram)
corPlot(measure.cor)
```



```{r feature engineering}
# Create head to height proportion of each individual
head.over.height <- final.df$head.height/final.df$height
final.df["head.over.height"]<-head.over.height
# Create head to foot length proportion of each individual

# Create arm.reach to height proportion of each individual
height.over.armreach <- final.df$height/final.df$arm.reach
final.df["height.over.armreach"]<-height.over.armreach

# Create floor to hip length to height proportion of each individual
leg.over.height <- final.df$floor.hip/final.df$height
final.df["leg.over.height"]<-leg.over.height

# Create floor to hip length to floor to knee-pit proportion of each individual

# Create foot length to hand length proportion of each individual

```

I want to explore possible relationships between ethnicity and measurements, and between gender and measurements.
I can possibly compare by race instead of ethnicity.
Difference between child and adults, female and male...

```{r boxplots}
# boxlop
height.m <- final.df$height[final.df$my.gender == 'm']
height.f <- final.df$height[final.df$my.gender == 'f']

boxplot(height.m, height.f,
main = "Boxplot of height comparision by gender",
names=c("male", "female"),
xlab = "Height(cm)",
col = c("orange", 'red'),
border = "brown",
notch = TRUE)

##############################
boxplot(height~my.ethnicity,
data = final.df,
main = "Boxplot of height comparision by ethnicity",
xlab = "Height(cm)",
col = "orange",
border = "brown",
notch = TRUE)

#############################
boxplot(floor.navel~my.ethnicity,
data = final.df,
main = "Boxplot of floor to navel comparision by ethnicity",
xlab = "Height(cm)",
col = "orange",
border = "brown",
notch = TRUE)
```

```{r distributions}
age.mean <- mean(final.df$age)
age.sd <- sd(final.df$age)

hist(final.df$age, xlab='age', col='orange', border='brown', probability = TRUE)
curve(dnorm(x, mean=age.mean, sd=age.sd), add=TRUE, col='red')

hist(final.df$height, xlab='height', col='orange', border='brown', probability = TRUE)
curve(dnorm(x, mean=mean(final.df$height), sd=sd(final.df$height)), add=TRUE, col='red')

hist(final.df$head.height, xlab='head height', col='orange', border='brown', probability = TRUE)
curve(dnorm(x, mean=mean(final.df$head.height), sd=sd(final.df$head.height)), add=TRUE, col='red')

hist(final.df$floor.hip, xlab='leg length', col='orange', border='brown', probability = TRUE)
curve(dnorm(x, mean=mean(final.df$floor.hip), sd=sd(final.df$floor.hip)), add=TRUE, col='red')

hist(final.df$arm.reach, xlab='arm reach', col='orange', border='brown', probability = TRUE)

hist(final.df$foot.length, xlab='foot length', col='orange', border='brown', probability = TRUE)
```

